title: <img src="https://readme-typing-svg.herokuapp.com?font=Boxed+Round&size=40&duration=4000&color=b5e853&center=true&vCenter=true&width=800&height=100&lines=El-Baraa+Radwan;Full-Stack+(MERN)+WEB+Developer" />
logo: /assets/img/logo.png
description: Full-Stack (MERN) Web Developer.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
